name: TestingPlugin
version: ${project.version}
main: xyz.ondercrew.testingplugin.TestingPlugin
api-version: 1.13
authors: [OnderCrew, PMH]
description: PMH's Minecraft Bukkit Plugin Tester
website: https://github.com/OnderCrew/testingPlugin
